{% set name = "opera-utils" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opera-utils-{{ version }}.tar.gz
  sha256: 5ecee0ad73cc4600e5aff065cdd1da46e73cd6a5c96a971657a5988c7cfe56e4

build:
  entry_points:
    - opera_utils = opera_utils.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - h5py >=1.10
    - numpy >=1.20
    - pooch >=1.7
    - shapely >=1.8

test:
  imports:
    - opera_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opera-adt/opera-utils
  summary: Miscellaneous utilities for working with OPERA data products
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/opera-adt/opera-utils

extra:
  recipe-maintainers:
    - scottstanie
