{% set name = "opera-utils" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb9c7850a6205cba992ae9b36904ff818e632acc4f1b6496787355aa711526d7

build:
  entry_points:
    - opera-utils = opera_utils.cli:cli_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - click >=7.0
    - h5py >=1.10
    - numpy >=1.20
    - pooch >=1.7
    - pyproj >=3.3
    - shapely >=1.8

test:
  imports:
    - opera_utils
  commands:
    - pip check
    - opera-utils --help
  requires:
    - pip

about:
  home: https://github.com/opera-adt/opera-utils
  summary: Miscellaneous utilities for working with OPERA data products
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/opera-adt/opera-utils

extra:
  recipe-maintainers:
    - scottstanie
    - mirzaees
    - gmgunter
