{% set name = "opera-utils" %}
{% set version = "0.23.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f68840fca5afa1ae56ba873c62099fa37463a66a035f4ba3d53235bf4c4d3e10

build:
  entry_points:
    - opera-utils = opera_utils.cli:cli_app
  noarch: python
  script: {{ PYTHON }} -m pip install .[disp] -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.9
    - tyro >=0.9
    - h5py >=1.10
    - numpy >=1.20
    - pooch >=1.7
    - pyproj >=3.3
    - shapely >=1.8
    - asf_search >=6.7
    - gdal >=3.8
    - libgdal-netcdf
    - rasterio >=1.3
    - affine
    - botocore
    - aiohttp
    - fsspec
    - h5netcdf
    - s3fs
    - tqdm
    - pandas
    - xarray
    - dask
    - zarr

test:
  imports:
    - opera_utils

  commands:
    - pip check
    - opera-utils --help
    - opera-utils search-l2 --help
    - opera-utils disp-s1-frame-bbox --help
    - opera-utils disp-s1-intersects --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opera-adt/opera-utils
  summary: Miscellaneous utilities for working with OPERA data products
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/opera-adt/opera-utils

extra:
  recipe-maintainers:
    - scottstanie
    - mirzaees
    - gmgunter
